trigger:
- v2

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- task: AzureCLI@1
  displayName: 'Deploy VoTT to Web'
  inputs:
    azureSubscription: 'PELITTLE TEAM - CSE DWR (d36d0808-a967-4f73-9fdc-32ea232fc81d)'
    scriptLocation: inlineScript
    inlineScript: './scripts/deploy-to-azure.sh'
