steps:
  - task: NodeTool@0
    displayName: 'Use Node 10.x'
    inputs:
      versionSpec: 10.x

  - bash: |  
      set -ex
      
      # clean install
      npm ci
      npm run release
      
      mkdir -p mac
      cp releases/vott*.dmg mac/
    displayName: Build

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: mac'
    inputs:
      PathtoPublish: mac
      ArtifactName: mac
