version: 1

update_configs:
  # Keep package.json (& lockfiles) up to date weekly
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"

    default_labels:
      - "dependency-update"
