name: "GitHub & Web Release [$(SourceBranchName)] - $(Date:yyyyMMdd)$(Rev:.r)"

trigger: none # manual queue only when we're ready to release
pr: none # disable CI build for PR

variables:
  azureSubscription: "pj-little-sub"
  DEV_STORAGE_ACCOUNT: 'vottdev'
  PROD_STORAGE_ACCOUNT: 'vott'
  DEV_URL: "https://vottdev.z5.web.core.windows.net/"
  PROD_URL: "https://vott.z22.web.core.windows.net/  (Recommended)"

stages:
- stage: version_bump_commit
  jobs:
    - template: templates/npm-version-bump.yml
      parameters:
        versionType: $(NPM_VERSION_TYPE)

- stage: github_release
  dependsOn: version_bump_commit
  jobs:
  - template: templates/create-github-release.yml
    parameters:
      GitHubConnection: 'GitHub connection' # defaults for any parameters that aren't specified
      repositoryName: '$(Build.Repository.Name)' # microsoft/VoTT
      isPreRelease: $(IS_PRERELEASE) # set when queuing build
      isDraft: $(IS_DRAFT)

- stage: web_release
  dependsOn: version_bump_commit
  jobs:
  - template: templates/create-web-release.yml
